services:
  - type: web
    name: laravel-app
    env: docker
    # dockerfilePath: nginx/Dockerfile
    # buildCommand: docker build --build-arg ENVIRONMENT=render -t ems-nginx .
    # startCommand: nginx -g 'daemon off;'
    plan: free
    envVars:
      - key: APP_ENV
        sync: false
      - key: APP_KEY
        sync: false
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
